name: master Build Matrix

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.8"

      - name: make
        run: make

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies via brew
        run: brew install qt@5 openssl

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.8"

      - name: make
        run: make build/kristall

  build_cmake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.8"

      - name: Install OpenSSL
        run: sudo apt install -y libssl-dev

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          build-dir: build

      - name: Build the project
        run: cmake --build build

# Disabled until both aqinstall and install-qt-action support the fixes…
#  build_windows:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: MasterQ32/install-qt-action@master
#      with:
#        version: '5.15.0'
#        host: 'windows'
#        target: 'desktop'
#        arch: 'win64_mingw81'
#        install-deps: 'true'
#        tools: 'tools_openssl_x64 qt.tools.openssl.win_x64;tools_openssl_src qt.tools.openssl'
#    - name: build and deploy
#      run: ./build-and-deploy.bat
#      working-directory: ./ci/
